import {
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Plus,
  Minus,
  Pencil,
  Trash2,
  Search,
  Download,
  Upload,
  RefreshCw,
  Settings,
  Star,
  Heart,
  Bell,
  Mail,
  Phone,
  User,
  Lock,
  Eye,
  EyeOff,
  Copy,
  Share2,
  ExternalLink,
  Filter,
  SlidersHorizontal,
  MoreHorizontal,
  MoreVertical,
  LogOut,
  LogIn,
  Home,
  Folder,
  File,
  Image,
  Link,
  Calendar,
  Clock,
  MapPin,
  Zap,
  ShieldCheck,
  Info,
  AlertTriangle,
  CircleAlert,
  CircleCheck,
  UserRound,
} from 'lucide-react'

const ICON_SIZE = 20

export const iconMap = {
  none: undefined,
  'arrow-right': <ArrowRight size={ICON_SIZE} />,
  'arrow-left': <ArrowLeft size={ICON_SIZE} />,
  'arrow-up': <ArrowUp size={ICON_SIZE} />,
  'arrow-down': <ArrowDown size={ICON_SIZE} />,
  check: <Check size={ICON_SIZE} />,
  'chevron-right': <ChevronRight size={ICON_SIZE} />,
  'chevron-left': <ChevronLeft size={ICON_SIZE} />,
  'chevron-down': <ChevronDown size={ICON_SIZE} />,
  'chevron-up': <ChevronUp size={ICON_SIZE} />,
  x: <X size={ICON_SIZE} />,
  plus: <Plus size={ICON_SIZE} />,
  minus: <Minus size={ICON_SIZE} />,
  pencil: <Pencil size={ICON_SIZE} />,
  'trash-2': <Trash2 size={ICON_SIZE} />,
  search: <Search size={ICON_SIZE} />,
  download: <Download size={ICON_SIZE} />,
  upload: <Upload size={ICON_SIZE} />,
  'refresh-cw': <RefreshCw size={ICON_SIZE} />,
  settings: <Settings size={ICON_SIZE} />,
  star: <Star size={ICON_SIZE} />,
  heart: <Heart size={ICON_SIZE} />,
  bell: <Bell size={ICON_SIZE} />,
  mail: <Mail size={ICON_SIZE} />,
  phone: <Phone size={ICON_SIZE} />,
  user: <User size={ICON_SIZE} />,
  lock: <Lock size={ICON_SIZE} />,
  eye: <Eye size={ICON_SIZE} />,
  'eye-off': <EyeOff size={ICON_SIZE} />,
  copy: <Copy size={ICON_SIZE} />,
  'share-2': <Share2 size={ICON_SIZE} />,
  'external-link': <ExternalLink size={ICON_SIZE} />,
  filter: <Filter size={ICON_SIZE} />,
  'sliders-horizontal': <SlidersHorizontal size={ICON_SIZE} />,
  'more-horizontal': <MoreHorizontal size={ICON_SIZE} />,
  'more-vertical': <MoreVertical size={ICON_SIZE} />,
  'log-out': <LogOut size={ICON_SIZE} />,
  'log-in': <LogIn size={ICON_SIZE} />,
  home: <Home size={ICON_SIZE} />,
  folder: <Folder size={ICON_SIZE} />,
  file: <File size={ICON_SIZE} />,
  image: <Image size={ICON_SIZE} />,
  link: <Link size={ICON_SIZE} />,
  calendar: <Calendar size={ICON_SIZE} />,
  clock: <Clock size={ICON_SIZE} />,
  'map-pin': <MapPin size={ICON_SIZE} />,
  zap: <Zap size={ICON_SIZE} />,
  'shield-check': <ShieldCheck size={ICON_SIZE} />,
  info: <Info size={ICON_SIZE} />,
  'alert-triangle': <AlertTriangle size={ICON_SIZE} />,
  'circle-alert': <CircleAlert size={ICON_SIZE} />,
  'circle-check': <CircleCheck size={ICON_SIZE} />,
  'user-round': <UserRound size={ICON_SIZE} />,
}

export type IconName = keyof typeof iconMap
export const iconOptions = Object.keys(iconMap).filter((k) => k !== 'none')
