// Stable type shim for `@ds/core/dist/components`.
//
// The React wrapper generated by @stencil/react-output-target imports the
// `Components` (and `JSX`) namespaces from `@ds/core/dist/components`, but
// Stencil's auto-generated `dist/components/index.d.ts` only re-exports the
// loader utilities (getAssetPath, defineCustomElement, etc.) — not those
// namespaces. This module augments that subpath by re-exporting both the
// generated runtime barrel and the component type namespaces.
//
// It is wired in via `compilerOptions.paths` in tsconfig.json so it only
// affects type resolution for `@ds/react`; the root `@ds/core` package
// contract is left untouched.
declare module '@ds/core/dist/components' {
  export * from '@ds/core/dist/components/index'
  export * from '@ds/core/dist/types/components'
}
